# ~/.config/hypr/hyprpaper.conf

# Global settings
ipc = on          # Keeps the "bridge" open for live changes
splash = false    # Removes the random text/quotes from the bottom

# New Block Syntax for your specific monitor
wallpaper {
    monitor =
    path = ~/.config/hypr/wallpapers/backiee-265661-landscape.jpg
}
