# ------------------------------------
# Paleta de Colores: Gruvbox (Dark Hard)
# ------------------------------------

# Colores Base
color_bg_main=#282828
color_fg_main=#EBDBB2
color_comment=#928374
color_selection_bg=#3C3836

# Colores Acento / ANSI Estándar (Dark Hard)
color_black=#282828
color_red=#CC241D
color_green=#98971A
color_yellow=#D79921
color_blue=#458588
color_magenta=#B16286
color_cyan=#689D6A
color_orange=#D65D0E
color_white=#A89984

color_black=#282828
color_red=#FB4934
color_green=#B8BB26
color_yellow=#FABD2F
color_blue=#83A598
color_magenta=#D3869B
color_cyan=#8EC07C
color_orange=#FE8019
