set -g mouse on

# change default prefix
unbind C-b
set -g prefix C-t
bind C-t send-prefix

unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g base-index 1
set -g pane-base-index 1

# set vi-mode to yank text
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'

# set-option -g status-position top
# set -g status-left ""
# set -g @catppuccin_window_number_position "right"
# set -g @catppuccin_window_current_number_color "#E5C07B"
# set -g @catppuccin_status_background "none"
# set -g @catppuccin_window_text "#W"
# set -g @catppuccin_window_current_text "#W"
# set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_fg}][#S]'

# Configure Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"
# Configure Online status
set -g @online_icon "ok"
set -g @offline_icon "nok"
# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#[bg=#282C34,fg=#E5C07B,none]"
set -ga status-left "#[bg=#E5C07B,fg=#282C34,none]  "
set -ga status-left "#[bg=#282C34,fg=#E5C07B,none]"
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_bg},fg=#ABB2BF,bold] #S },#{#[bg=#{@thm_bg},fg=#E5C07B,bold] #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#282C34,fg=#98C379,none]"
set -ga status-left "#[bg=#98C379,fg=#282C34,none]  "
set -ga status-left "#[bg=#282C34,fg=#98C379,none]"
set -ga status-left "#[bg=#{@thm_bg},fg=#98C379,bold] #{pane_current_command} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#282C34,fg=#C678DD,none]#{?window_zoomed_flag,,}"
set -ga status-left "#[bg=#C678DD,fg=#282C34,none]#{?window_zoomed_flag,  ,}"
set -ga status-left "#[bg=#282C34,fg=#C678DD,none]#{?window_zoomed_flag,,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#C678DD,bold] #{?window_zoomed_flag,zoom,}"
# status right look and feel
set -g status-right-length 100
set -g status-right ""
# set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_blue}] 󰭦 %Y-%m-%d 󰅐 %H:%M "
# set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}, none]│"
set -ga status-right "#[bg=#282C34,fg=#61AFEF,none]"
set -ga status-right "#[bg=#64AFEF,fg=#282C34,none]  " # fg=#{@value}
set -ga status-right "#[bg=#282C34,fg=#61AFEF,none]"
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_blue}] #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
# Configure Tmux
set -g status-position top
set -g status-style "bg=#{@thm_bg}"
set -g status-justify "absolute-centre"
# window look and feel
set -wg automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_rosewater}"
set -g window-status-last-style "bg=#{@thm_bg},fg=#{@thm_peach}"
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"
set -gF window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"

set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_peach},fg=#{@thm_bg},bold"
run '~/.tmux/plugins/tpm/tpm'
